# Generated by Django 3.0.8 on 2020-07-05 09:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20200705_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='posted_date',
            field=models.CharField(default=datetime.datetime(2020, 7, 5, 9, 48, 48, 985948), max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.CharField(blank=True, default='2DB22E', max_length=50, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='last_posted_date',
            field=models.CharField(default=datetime.datetime(2020, 7, 5, 9, 48, 48, 985531), max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='posted_date',
            field=models.CharField(default=datetime.datetime(2020, 7, 5, 9, 48, 48, 985491), max_length=50),
        ),
    ]
