# Generated by Django 3.0.8 on 2020-07-05 10:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20200705_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_id',
            field=models.CharField(blank=True, default='864518', max_length=50, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='posted_date',
            field=models.CharField(default=datetime.datetime(2020, 7, 5, 10, 58, 7, 281432), max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='last_posted_date',
            field=models.CharField(default=datetime.datetime(2020, 7, 5, 10, 58, 7, 280996), max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_id',
            field=models.CharField(blank=True, default='7ACC15', max_length=50, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='posted_date',
            field=models.CharField(default=datetime.datetime(2020, 7, 5, 10, 58, 7, 280956), max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(blank=True, default='C3ED6D', max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
