# Generated by Django 3.0.8 on 2020-07-05 12:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20200705_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_id',
            field=models.CharField(blank=True, default='7742F8', max_length=50, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='posted_date',
            field=models.CharField(default=datetime.datetime(2020, 7, 5, 12, 8, 56, 951716), max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='last_posted_date',
            field=models.CharField(default=datetime.datetime(2020, 7, 5, 12, 8, 56, 951248), max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_id',
            field=models.CharField(blank=True, default='91A949', max_length=50, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='posted_date',
            field=models.CharField(default=datetime.datetime(2020, 7, 5, 12, 8, 56, 951201), max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(blank=True, default='1571D6', max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
