# Generated by Django 3.0.8 on 2020-07-08 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_auto_20200707_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='parent_id',
            field=models.CharField(default='none', max_length=50),
        ),
    ]
