# Generated by Django 3.0.8 on 2020-07-09 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_auto_20200709_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='edited',
            field=models.CharField(default='posted', max_length=10),
        ),
        migrations.AlterField(
            model_name='post',
            name='edited',
            field=models.CharField(default='posted', max_length=10),
        ),
    ]
