# Generated by Django 3.0.8 on 2020-07-09 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_rate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rate',
            old_name='commend_id',
            new_name='comment_id',
        ),
        migrations.AlterField(
            model_name='rate',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
