# Generated by Django 3.0.8 on 2020-07-09 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_auto_20200709_2009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rate',
            name='comment_id',
        ),
        migrations.RemoveField(
            model_name='rate',
            name='username',
        ),
    ]
