# Generated by Django 3.0.8 on 2020-07-09 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_auto_20200709_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='username',
            field=models.CharField(default='', max_length=50),
        ),
    ]
