# Generated by Django 3.0.8 on 2020-07-09 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_rate_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='username',
            field=models.CharField(default='guest', max_length=50),
        ),
    ]
