# Generated by Django 3.0.8 on 2020-07-09 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_auto_20200709_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='comment_id',
            field=models.ForeignKey(default='guest', on_delete=django.db.models.deletion.CASCADE, to='myapp.Comment'),
        ),
    ]
