# Generated by Django 3.0.8 on 2020-07-18 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0036_user_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('game_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('opponent', models.CharField(max_length=50)),
                ('result', models.CharField(max_length=4)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
